import { EXT_LEVEL1_COMPONENTS_MAPPING as EXT_LEVEL1_CUSTOMERS_CUSTOMER_COMPONENTS_MAPPING } from '../customers/customer/extensions/ext-level1';

export const EXT_LEVEL1_ALL_START_COMPONENTS_MAPPING = [
  ...EXT_LEVEL1_CUSTOMERS_CUSTOMER_COMPONENTS_MAPPING
];
